### PR TITLE
feat: Continuous process rename when old bundle id android not correct

### PR DESCRIPTION
**Pull request by CaoGiaHieu-dev**

### CODE REVIEW

**Comment by CaoGiaHieu-dev** [comment]
@OutdatedGuy Hi . can you check this pr ?

**Comment by OutdatedGuy** [comment]
Hi, can you elaborate on the changes and also fix the title and description of the PR?

**Comment by OutdatedGuy** [comment]
> For real case if some one want to change with multi flavor , they must to config the first yml with `override_old_package` and other without `override_old_package` .

I don't understand what this means but your changes will create a standard `MainActivity.java` or `MainActivity.kt` file even if the `override_old_package` is wrong. Wouldn't that affect users who accidentally put a wrong `override_old_package`. They wouldn't get their old code shifted and wouldn't know if the error is not shown.

**Comment by CaoGiaHieu-dev** [comment]
> Wouldn't that affect users who accidentally put a wrong `override_old_package`. They wouldn't get their old code shifted and wouldn't know if the error is not shown.

it only need to show warning , not terminal cli

> I don't understand what this means 

For example:
 - Lets try to create a new flutter project with bundle id `com.example.example` .
 - Create .yaml config for each flavors (dev, staging ,prod) with bundle id `com.test.test.{plavor}`
Cause : If i want to use `override_old_package` , i need to set `com.example.example` to the first flavor that i run
Expect : i want to set`override_old_package` fot all flavor config so that i can run which ever i want so that i dont need to worry about what i run first

**Comment by OutdatedGuy** [comment]
@CaoGiaHieu-dev does your `MainActivity.kt` file have additional code that you have added? If it is just the standard template without any modifications, you don't have to add `override_old_package` at all, and it would work just like how you want in the PR.

**Pull request closed without merging**
